README.MD file updated
computerclubkec/computerclubkec.github.io pull request #11
Opened 2024-10-02 16:58 UTC by aakashrana007

I've updated README.MD file and which is yet to be updated but since I have made a layout, it'd be easier later.

2024-10-02 17:05 UTC, gaurovgiri requested changes

2024-10-02 17:05 UTC, gaurovgiri commented on README.md
> +### License
No license is required for now.

2024-10-02 17:05 UTC, gaurovgiri commented on README.md
> +`docker-compose up`
```suggestion
`docker-compose up` or `docker compose up`
```

2024-10-02 17:05 UTC, gaurovgiri commented on README.md
> +
Display the contributors.

2024-10-02 17:06 UTC, gaurovgiri requested changes

2024-10-02 17:06 UTC, gaurovgiri commented on README.md
> +
add tailwind as well

2024-10-03 17:06 UTC, gaurovgiri approved these changes
LGTM!

2024-10-03 17:07 UTC, KhatiwadaPrajwal056 approved these changes
LGTM

2024-10-03 17:07 UTC, prabhavpokharel approved these changes
LGTM

2024-10-03 17:07 UTC, merged